"""Ready to go contexts ready to be imported"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_contexts.ipynb.

# %% auto 0
__all__ = ['read_gist', 'nbclassic_server', 'minai', 'docker', 'fastlite_sqlutils', 'fasthtml', 'fastcore', 'claudette']

# %% ../nbs/01_contexts.ipynb 3
from httpx import get
from playwrightnb import url2md
from functools import partial
from toolslm.download import find_docs, read_docs
from fastcore.all import *

# %% ../nbs/01_contexts.ipynb 4
def read_gist(s, user): return get(f'https://gist.githubusercontent.com/{user}/{s}').text

# %% ../nbs/01_contexts.ipynb 5
def nbclassic_server(): 
    return {'nbclassic_server': url2md('https://nbclassic.readthedocs.io/en/latest/nbclassic.html','.bd-article')}

# %% ../nbs/01_contexts.ipynb 6
def minai():
    ctxs = {'framework':'f242de7c00ace2db18771f9999a2d2fa/raw/73d6367f74d6678b1d1752332e86f110f5dded57',
            'course_nbs': 'a9ac18696ccc8379b7b0a4e0847826cf/raw/77b31753f879e2b9769e1630fad76a4c3936d6da',
            'course_summary': '08684d1aa641ee0686d7b620e66de24c/raw/9290a38676def861aa6fdb7917d6793b3dd67ccd'}
    _fn = bind(read_gist,user='isaac-flath')
    print("WARNING: Reading from gists not a dynamic source.")
    return {k:_fn(v) for k,v in ctxs.items()}

# %% ../nbs/01_contexts.ipynb 7
def docker():
    ctxs = {'compose_file':'https://docs.docker.com/reference/compose-file/',
            'docker_cli':'https://docs.docker.com/reference/cli/docker/',
            'docker_compose_cli':'https://docs.docker.com/reference/cli/docker/compose/',
            'dockerd':'https://docs.docker.com/reference/cli/dockerd/',
            'dockerhub':'https://docs.docker.com/reference/api/hub/latest/'}
    return {k: url2md(url, '.prose') for kv in ctxs.items}

# %% ../nbs/01_contexts.ipynb 8
def fastlite_sqlutils():
    return {
        'fastlite_kw': get('https://raw.githubusercontent.com/AnswerDotAI/fastlite/refs/heads/main/fastlite/kw.py').text,
        'fastlite_core': get('https://raw.githubusercontent.com/AnswerDotAI/fastlite/refs/heads/main/fastlite/core.py').text,
        'fastlite_docs': read_docs('https://answerdotai.github.io/fastlite/'),
        'sqlite_utils_docs': url2md('https://sqlite-utils.datasette.io/en/stable/python-api.html','#sqlite-utils-python-library')
    }

# %% ../nbs/01_contexts.ipynb 9
def fasthtml():
    return {
        'fasthtml_docs': read_docs('https://docs.fastht.ml'),
        'hypermedia_summary': read_gist('d5dc25001d70f5ceb20d115f586662d6/raw/80e427ace28dfc8a576617c5903cc2e12496ba4f','isaac-flath')
    }

# %% ../nbs/01_contexts.ipynb 10
def fastcore(): 
    return {'fastcore_docs': read_docs('https://fastcore.fast.ai/')}

# %% ../nbs/01_contexts.ipynb 11
def claudette():
    ctxs = {
        'async': 'https://claudette.answer.ai/async.html.md',
        'core': 'https://claudette.answer.ai/core.html.md',
        'toolloop': 'https://claudette.answer.ai/toolloop.html.md'
    }
    return {k: get(url).text for k, url in ctxs.items()}
