"""Ready to go contexts ready to be imported"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_contexts.ipynb.

# %% auto 0
__all__ = ['nbclassic_server', 'docker', 'fastlite_sqlutils', 'fasthtml', 'fastcore', 'claudette']

# %% ../nbs/01_contexts.ipynb 3
from .read import *

# %% ../nbs/01_contexts.ipynb 6
def nbclassic_server(): 
    return {'nbclassic_server': read_url('https://nbclassic.readthedocs.io/en/latest/nbclassic.html',sel='.bd-article')}

# %% ../nbs/01_contexts.ipynb 9
def docker():
    ctxs = {'compose_file':'https://docs.docker.com/reference/compose-file/',
            'docker_cli':'https://docs.docker.com/reference/cli/docker/',
            'docker_compose_cli':'https://docs.docker.com/reference/cli/docker/compose/',
            'dockerd':'https://docs.docker.com/reference/cli/dockerd/',
            'dockerhub':'https://docs.docker.com/reference/api/hub/latest/'}
    return {k: read_url(v, sel='.prose') for k,v in ctxs.items()}

# %% ../nbs/01_contexts.ipynb 12
def fastlite_sqlutils():
    return {
        'fastlite_index': read_url('https://answerdotai.github.io/fastlite/index.html.md'),
        'fastlite_core': read_url('https://answerdotai.github.io/fastlite/core.html.md'),
        'sqlite_utils_docs': read_url('https://sqlite-utils.datasette.io/en/stable/python-api.html',
                                      sel='#sqlite-utils-python-library')
    }

# %% ../nbs/01_contexts.ipynb 15
def fasthtml():
    return {
        'fasthtml_llms-ctx': read_url('https://docs.fastht.ml/llms-ctx.txt'),
        'hypermedia_summary': read_gist('https://gist.github.com/jph00/4ad7d35ad79013aded41b5ba535a12a3')
    }

# %% ../nbs/01_contexts.ipynb 18
def fastcore(): 
    return {'llms-ctx': read_url('https://fastcore.fast.ai/llms-ctx.txt')}

# %% ../nbs/01_contexts.ipynb 21
def claudette():
    ctxs = {
        'async': 'https://claudette.answer.ai/async.html.md',
        'core': 'https://claudette.answer.ai/core.html.md',
        'toolloop': 'https://claudette.answer.ai/toolloop.html.md'
    }
    return {k: read_url(url) for k, url in ctxs.items()}
