"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['read_gist', 'nbclassic_server', 'docker', 'fasthtml', 'fastcore', 'claudette', 'discord']

# %% ../nbs/00_core.ipynb 3
from httpx import get
from playwrightnb import url2md
from toolslm.download import find_docs, read_docs

# %% ../nbs/00_core.ipynb 4
def read_gist(user,s): return get(f'https://gist.githubusercontent.com/{user}/{s}').text

# %% ../nbs/00_core.ipynb 5
def nbclassic_server(): return url2md('https://nbclassic.readthedocs.io/en/latest/nbclassic.html','.bd-article')

# %% ../nbs/00_core.ipynb 6
def docker(): 
    urls = {'Dockerfile':'https://docs.docker.com/reference/dockerfile/',
            'Composefile':'https://docs.docker.com/reference/compose-file/',
            'docker_cli':'https://docs.docker.com/reference/cli/docker/',
            'compose_cli':'https://docs.docker.com/reference/cli/docker/compose/',
            'daemon':'https://docs.docker.com/reference/cli/dockerd/',
            'dockerghub':'https://docs.docker.com/reference/api/hub/latest/'}
    return {k:url2md(v,'.prose') for k,v in urls.items()}

# %% ../nbs/00_core.ipynb 7
def fasthtml():return read_docs('https://docs.fastht.ml')

# %% ../nbs/00_core.ipynb 8
def fastcore(): return read_docs('https://fastcore.fast.ai/')

# %% ../nbs/00_core.ipynb 9
def claudette():
    urls = ['https://claudette.answer.ai/async.html.md',
           'https://claudette.answer.ai/core.html.md',
           'https://claudette.answer.ai/toolloop.html.md',
           'https://claudette.answer.ai/async.html.md']
    return {url.split('/')[-1].split('.')[0]: get(url).text for url in urls}        

# %% ../nbs/00_core.ipynb 10
def discord():
    gists = {
        'app': '97e08aa4c97129d942ceaf44ee37238a/raw/de856c4390afc7ea2302c6c89de3bf30756528c9/discord-app-cmd.md',
        'oauth': 'd9bf85f7862c2c0108df392244b9e1c4/raw/448e4403569cfbf62b617fce24c1a7c04435e82f/discord-oauth.md',
        'user': '2a3c75353356242c6809a29b9e8b68ca/raw/108ad0a93ac1a18b91f685f9b9445952b1bd5935/discord-app-user.md',
        'interact': 'a294f7de6834302c6bda6c5308223e9d/raw/53abc463fadd4ef8742be88902c96dd3c0c9522b/discord-interact.md'
    }
    return {k: read_gist('jph00',v) for k, v in gists.items()}
