"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['read_gist', 'nbclassic_server', 'minai', 'docker', 'fastlite_sqlutils', 'fasthtml', 'fastcore', 'claudette']

# %% ../nbs/00_core.ipynb 3
from httpx import get
from playwrightnb import url2md
from functools import partial
from toolslm.download import find_docs, read_docs
from fastcore.all import *

# %% ../nbs/00_core.ipynb 4
def read_gist(s, user): return get(f'https://gist.githubusercontent.com/{user}/{s}').text

# %% ../nbs/00_core.ipynb 5
def nbclassic_server(): return url2md('https://nbclassic.readthedocs.io/en/latest/nbclassic.html','.bd-article')

# %% ../nbs/00_core.ipynb 6
def minai():
    framework = 'f242de7c00ace2db18771f9999a2d2fa/raw/73d6367f74d6678b1d1752332e86f110f5dded57'
    course_nbs = 'a9ac18696ccc8379b7b0a4e0847826cf/raw/77b31753f879e2b9769e1630fad76a4c3936d6da'
    course_summary = '08684d1aa641ee0686d7b620e66de24c/raw/9290a38676def861aa6fdb7917d6793b3dd67ccd'
    _fn = bind(read_gist,user='isaac-flath')
    return list(map(_fn,(framework,course_nbs,course_summary)))

# %% ../nbs/00_core.ipynb 7
def docker():
    urls = [
        'https://docs.docker.com/reference/dockerfile/',
        'https://docs.docker.com/reference/compose-file/',
        'https://docs.docker.com/reference/cli/docker/',
        'https://docs.docker.com/reference/cli/docker/compose/',
        'https://docs.docker.com/reference/cli/dockerd/',
        'https://docs.docker.com/reference/api/hub/latest/']
    return tuple(map(lambda url: url2md(url, '.prose'), urls))

# %% ../nbs/00_core.ipynb 8
def fastlite_sqlutils():
    fastlite_kw = get('https://raw.githubusercontent.com/AnswerDotAI/fastlite/refs/heads/main/fastlite/kw.py')
    fastlite_core = get('https://raw.githubusercontent.com/AnswerDotAI/fastlite/refs/heads/main/fastlite/core.py')
    fastlite_docs = read_docs('https://answerdotai.github.io/fastlite/')
    sqlite_utils_docs = url2md('https://sqlite-utils.datasette.io/en/stable/python-api.html','#sqlite-utils-python-library')
    return fastlite_kw, fastlite_core, fastlite_docs, sqlite_utils_docs

# %% ../nbs/00_core.ipynb 9
def fasthtml():
    hypermedia_summary = read_gist('d5dc25001d70f5ceb20d115f586662d6/raw/80e427ace28dfc8a576617c5903cc2e12496ba4f','isaac-flath')
    return read_docs('https://docs.fastht.ml'),hypermedia_summary

# %% ../nbs/00_core.ipynb 10
def fastcore(): 
    return read_docs('https://fastcore.fast.ai/'), 

# %% ../nbs/00_core.ipynb 11
def claudette():
    urls = ['https://claudette.answer.ai/async.html.md',
           'https://claudette.answer.ai/core.html.md',
           'https://claudette.answer.ai/toolloop.html.md',
           'https://claudette.answer.ai/async.html.md']
    return [get(url).text for url in urls]
