"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['read_gist', 'nbclassic_server', 'fasthtml', 'fastcore', 'claudette']

# %% ../nbs/00_core.ipynb 3
from httpx import get
from playwrightnb import url2md
from functools import partial
from toolslm.download import find_docs, read_docs
from fastcore.all import *

# %% ../nbs/00_core.ipynb 4
def read_gist(s, user): return get(f'https://gist.githubusercontent.com/{user}/{s}').text

# %% ../nbs/00_core.ipynb 5
def nbclassic_server(): return url2md('https://nbclassic.readthedocs.io/en/latest/nbclassic.html','.bd-article')

# %% ../nbs/00_core.ipynb 9
def fasthtml():
    hypermedia_summary = read_gist('d5dc25001d70f5ceb20d115f586662d6/raw/80e427ace28dfc8a576617c5903cc2e12496ba4f','isaac-flath')
    return read_docs('https://docs.fastht.ml'),hypermedia_summary

# %% ../nbs/00_core.ipynb 10
def fastcore(): 
    return read_docs('https://fastcore.fast.ai/'), 

# %% ../nbs/00_core.ipynb 11
def claudette():
    urls = ['https://claudette.answer.ai/async.html.md',
           'https://claudette.answer.ai/core.html.md',
           'https://claudette.answer.ai/toolloop.html.md',
           'https://claudette.answer.ai/async.html.md']
    return [get(url).text for url in urls]
