"""Read X for llm context"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_read.ipynb.

# %% auto 0
__all__ = ['read_gist']

# %% ../nbs/00_read.ipynb 3
from httpx import get

# %% ../nbs/00_read.ipynb 4
def read_gist(s, user): 
    # This should just be copy/paste url instead
    return get(f'https://gist.githubusercontent.com/{user}/{s}').text
